apiVersion: v1
kind: Service
metadata:
  name: waya-repository-v2
  labels:
    app: waya-repository-v2
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: waya-repository-v2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: waya-repository-v2
  labels:
    app: waya-repository-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: waya-repository-v2
  template:
    metadata:
      labels:
        app: waya-repository-v2
    spec:
      containers:
      - name: waya-repository-v2
        image: 863852973330.dkr.ecr.eu-west-2.amazonaws.com/waya-repository:imgtag
        resources:
          requests:
            memory: "200Mi"
        envFrom:
        - configMapRef:
            name: common-services-config
        ports: 
        - name: http
          containerPort: 80 
        volumeMounts:
        - name: config-file
          mountPath: "/app/application-cfgprofile.yml"  # "secret-file" file will be created in "/app" directory
          subPath: application.yml
        - name: tz-lagos
          mountPath: /etc/localtime
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node.kubernetes.io/description
                operator: In
                values:
                - corebanking-cfgprofile
                - wayabank-cfgprofile   
      volumes:
        - name: config-file
          secret:
            secretName: waya-repository-config-file # name of the Secret
        - name: tz-lagos
          hostPath:
            path: /usr/share/zoneinfo/Africa/Lagos
