server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /temporal-service
spring:
   application:
      name: temporal-wallet-service
      
   jpa:
     hibernate:
       ddl-auto: update
     properties:
       hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          show-sql: true
          jdbc:
            time_zone: UTC
     open-in-view: false
    
   devtools:
       livereload:
           enabled: false
   jackson:
      serialization:
         fail-on-empty-beans: false
         
   datasource:
        url:  ${POSTGRES_URL}
        username: ${POSTGRES_USERNAME}
        password: ${POSTGRES_PASSWORD}
        driver-class-name: org.postgresql.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}
    service-url:
      default-zone: ${EUREKA_SERVER_URL}
  instance:
    preferIpAddress: true

waya:
   wallet:
       auth: WAYA-AUTHENTICATION-SERVICE
       authurl: ${AUTH_SERVICE}
       mifos: WAYA-WALLET-SERVICE
       mifosurl: ${MIFOS-SERVICE}
       productcode: ${SBPRODUCT}
       commissioncode: ${COMMPRODUCT}
       wayaglCode: ${SBGLCODE}
       wayacommglCode: ${COMMGLCODE}
       
   card:
     cardurl: ${CARD-SERVICE}
     service: WAYA-CARD-SERVICE
     contacturl: ${CONTACT-SERVICE}
   contact:
      service: WAYA-CONTACT-SERVICE
   account:
       accounturl: ${ACCOUNT-SERVICE}
       service: WAYA-ACCOUNT-SERVICE
   sms:
     atalking: ${AFRICATALKING}
     infobip: ${INFOBIP}
     twilio: ${TWILIO}
     
##=========================================MySQL
#spring.datasource.url=jdbc:mysql://localhost:3306/waya_db?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
#spring.datasource.username=tbaadm
#spring.datasource.password=mysqlAdmin@123
## The SQL dialect makes Hibernate generate better SQL for the chosen database
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
#==========================================
#spring.datasource.url=jdbc:postgresql://localhost:5432/waya-wallet-service
#spring.datasource.username=postgres
#spring.datasource.password=jango123

#server:
#  port: 9009
#
#spring:
#  application:
#    name: temporal-wallet-service
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
#    open-in-view: false #this config disables database queries which  may be performed during view rendering
#  datasource:
#    url: jdbc:postgresql://db-postgresql-sfo2-54806-do-user-4419539-0.b.db.ondigitalocean.com:25060/WayaPayChatTemporalWalletDB
#    username: WayaPayChat2020
#    password: gh9shfit2m53g4xz
#    initialization-mode: always
#    driverClassName: org.postgresql.Driver
#    continue-on-error: true
#    hikari:
#      initialization-fail-timeout: 60000
#    initialize=false:
#
#
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://46.101.41.187:8761/eureka
#  instance:
#    preferIpAddress: true
#    hostname: localhost
