server:
  port: 80
  servlet:
    context-path: /temporal-service
spring:
   application:
      name: temporal-service
      
   jpa:
     hibernate:
       ddl-auto: update
     properties:
       hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          show-sql: true
          jdbc:
            time_zone: UTC
     open-in-view: false
    
   devtools:
       livereload:
           enabled: false
   jackson:
      serialization:
         fail-on-empty-beans: false
         
   datasource:
        url:  jdbc:postgresql://postgresdb:5432/temporal-service?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: pONvagaJf3BTbu9l
        driver-class-name: org.postgresql.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service/eureka
    service-url:
      default-zone: http://eureka-service/eureka
  instance:
    preferIpAddress: true

waya:
   wallet:
       auth: AUTHENTICATION-SERVICE
       authurl: ${CONFIG_BASEURL_AUTH:http://68.183.60.114:8059/api/v1}
       mifos: MIFOS-WALLET-SERVICE
       mifosurl: ${CONFIG_BASEURL_MWALLET:http://46.101.41.187:91960}
       productcode: ${CONFIG_PRODUCT_SAVINGS:SB601}
       commissioncode: ${CONFIG_PRODUCT_COMMISSION:SB901}
       wayaglCode: ${CONFIG_PRODUCT_SAVINGS_CODE:21200}
       wayacommglCode: ${CONFIG_PRODUCT_COMMISSION_CODE:21105}
       
   card:
     cardurl: ${CONFIG_BASEURL_CARD:http://157.230.223.54:3020/card-service/api}
     service: CARD-SERVICE
     contacturl: ${CONFIG_BASEURL_CONTACT:http://46.101.41.187:8065/contact-service/contact}
   contact:
      service: CONTACT-SERVICE
   account:
       accounturl: ${CONFIG_BASEURL_VIRACCOUNT:http://46.101.41.187:7090/account-creation-service/api}
       service: ACCOUNT-SERVICE
#   sms:
#     atalking: ${AFRICATALKING}
#     infobip: ${INFOBIP}
#     twilio: ${TWILIO}