server:
  port: 80
  servlet:
    context-path: /
spring:
   application:
      name: temporal-service
      
   jpa:
     hibernate:
       ddl-auto: update
     properties:
       hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          show-sql: true
          jdbc:
            time_zone: UTC
     open-in-view: false
    
   devtools:
       livereload:
           enabled: false
   jackson:
      serialization:
         fail-on-empty-beans: false
         
   datasource:
        url:  jdbc:postgresql://postgresdb:5432/temporal-service?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: pONvagaJf3BTbu9l
        driver-class-name: org.postgresql.Driver
   flyway:
      baselineOnMigrate: true
      locations: classpath:db/migration
      schemas: public
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service/eureka
    service-url:
      default-zone: http://eureka-service/eureka
  instance:
    preferIpAddress: true

waya:
   wallet:
       auth: AUTHENTICATION-SERVICE
       authurl: ${CONFIG_BASEURL_AUTH:https://services.staging.wayabank.ng/auth-service/api/v1} 
       mifos: MIFOS-WALLET-SERVICE
       mifosurl: ${CONFIG_BASEURL_MWALLET:https://services.staging.wayabank.ng/wallet-service}
       productcode: ${CONFIG_PRODUCT_SAVINGS:SB601}
       commissioncode: ${CONFIG_PRODUCT_COMMISSION:SB901}
       wayaglCode: ${CONFIG_PRODUCT_SAVINGS_CODE:21200}
       wayacommglCode: ${CONFIG_PRODUCT_COMMISSION_CODE:21105}
       
   card:
     cardurl: ${CONFIG_BASEURL_CARD:https://services.staging.wayabank.ng/card-service}
     service: CARD-SERVICE
     contacturl: ${CONFIG_BASEURL_CONTACT:https://services.staging.wayabank.ng/contact-service}
   contact:
      service: CONTACT-SERVICE
   account:
       accounturl: ${CONFIG_BASEURL_VIRACCOUNT:https://services.staging.wayabank.ng/account-service}
       service: ACCOUNT-SERVICE
#   sms:
#     atalking: ${AFRICATALKING}
#     infobip: ${INFOBIP}
#     twilio: ${TWILIO}
   notification:
      service: NOTIFICATION-SERVICE
      notificationurl: ${CONFIG_BASEURL_NOTIFICATION:https://services.staging.wayabank.ng/notification-service}
   receipt:
      service: RECEIPT-SERVICE
      receipturl: ${CONFIG_BASEURL_RECEIPT:https://services.staging.wayabank.ng/transaction-receipt}
   service:
     username: tbaadm@wayapaychat.com
     password: fintemp@#123