package com.wayapaychat.temporalwallet.enumm;

public enum ReportType {
    TRANSACTION,PAYMENT_REQUEST,BILLS_PAYMENT,WITHDRAWAL,DEPOSIT,
    INTERNAL_TRANSFERS,NON_WAYA_TRANSFER, USERS_DATAS, WAYAOFFICIAL, WITHDRAWAL_WAYAOFFICIAL,
    INTERNAL_TRANSFERS_WAYAOFFICIAL,


}
